<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* help@getflywheel.com.                                                           */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'http://');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '128M');




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db0662631695');
define('DB_USER', 'fw8644743707');
define('DB_PASSWORD', 'm8z0szdIdorZEjm64cYCttx6MOkhu1');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix  = 'wp_xf8ansai0p_';






/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          'uqe:d$bJ2&x9=1A)b#1#,d+|8?]mD0rYil!/PgKY)[ceunHoYE%6+cXnEZ#_k*`C');
define('SECURE_AUTH_KEY',   'w&V1SvgU@{Y8fN9R+n:tl$Uzgq|)`Ls&zgvlO-p/68r*#Z`9HnNUU1?&_Bf1QA6P');
define('LOGGED_IN_KEY',     '6aMR|Omv|3,DCzVHWFwI}tqxe>,fsH!eA$}=MO:Dfk&kixxYF^&*>4zQ9u9EJgwz');
define('NONCE_KEY',         '%3?.X`#BChU[CCME_b9F2Jol#3K%6;c=!W#A>_IF/]BzhUhi#,bM+fROJ6x:(c9,');
define('AUTH_SALT',         '-}q)z:V2B:77}EskfzBb/~L8fbu:5H*cJ+U+bYDZh3<t0oFaFM1PcipO0xs%Z@{,');
define('SECURE_AUTH_SALT',  'uDud#=@jW-A6@[;R*61ou}Q>zS!]&$^VsN]Fht!+iLjZs]_9V9e^4n@*F]]1(@vz');
define('LOGGED_IN_SALT',    'AJxP].!<N(+(=pt_gOG,^g,xvNkQ:*Iab)-S>fi?y?eHS@My`7@>i:=up:8%6WUO');
define('NONCE_SALT',        'f~QX{c5*ftRZTHue9.)qiLr4v-n{D`s~n2+Vc%)vim<;ow:&2%P:)+_6!ie[<wH&');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);
define('WP_DEBUG_LOG', false);




/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
